name: Sonar Quarkus

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '17'
        type: string
      sonar_organization:
        description: 'SonarCloud organization'
        required: true
        type: string
        default: ${{ github.repository_owner }}
      sonar_host:
        description: 'SonarCloud host'
        required: true
        type: string
        default: 'https://sonarcloud.io'

# TODO
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: SonarCloud Scan
        run: mvn -B verify sonar:sonar -Dsonar.organization=${{ inputs.sonar_organization }} -Dsonar.host.url=${{ inputs.sonar_host }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
