name: Quarkus Test

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '17'
        type: string

jobs:
  test-jvm:
    env:
      MAVEN_OPTS: '--batch-mode --errors --fail-at-end --show-version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: Test with Maven (verify)
        run: ./mvnw verify 
  test-native:
    env:
      MAVEN_OPTS: '--batch-mode --errors --fail-at-end --show-version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          graalvm-version: '21.3.0'
      - name: Test with Maven (verify)
        run: ./mvnw clean verify -Pnative
