name: Verify commit

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    uses: food2gether/workflows/.github/workflows/backend-push.yaml@main
