name: Publish Quarkus Image

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '17'
        type: string
      version:
        description: 'Application version'
        required: true
        type: string
    secrets:
      gh_token:
        description: 'GitHub Token with permissions to push to ghcr.io'
        required: true

env:
  MAVEN_ARGS: '--batch-mode -T 1C --errors --fail-at-end --show-version -DskipTests'

jobs:
  publish-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: Build Quarkus app
        run: ./mvnw package -Pnative
      - name: Generated image metadata
        id: meta
        with: docker/metadata-action@v5
      - name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: src/main/docker/Dockerfile.native-micro
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.version }}-native
            ghcr.io/${{ github.repository }}:${{ inputs.version }}
            ${{ github.event.isPrerelease && format('ghcr.io/{0}:latest-native', github.repository) || '' }}
            ${{ github.event.isPrerelease && format('ghcr.io/{0}:latest', github.repository) || '' }}
          labels: |
            ${{ steps.meta.outputs.labels }}
  publish-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: Publish Quarkus Image
        run: ./mvnw package 
      - name: Generated image metadata
        id: meta
        with: docker/metadata-action@v5
      - name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: src/main/docker/Dockerfile.jvm
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.version }}-jvm
            ${{ github.event.isPrerelease && format('ghcr.io/{0}:latest-jvm', github.repository) || '' }}
          labels: |
            ${{ steps.meta.outputs.labels }}