name: Verify push to protected branch

on:
  workflow_call:
    inputs:
      sonar-project:
        description: 'Sonar Project Key'
        required: true
        type: string
    secrets:
      sonar-token:
        description: 'Sonar Token'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-native:
    uses: food2gether/workflows/.github/workflows/maven-test.yaml@main
    with:
      java_version: '17'
      profile: native
  test-jvm:
    uses: food2gether/workflows/.github/workflows/maven-test.yaml@main
    with:
      java_version: '17'
      test_results_artifact_key: test-results
  sonar:
    needs: test-jvm
    uses: food2gether/workflows/.github/workflows/maven-sonar.yaml@main
    with:
      java_version: '17'
      test_results_artifact_key: test-results
      sonar_project_key: ${{ inputs.sonar-project }}
      # Branch analysis parameters should not be needed for intregated CIs (like GitHub Actions)
    secrets:
      sonar_token: ${{ secrets.sonar-token }}