name: Sonar Scan

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '17'
        type: string
      profile:
        description: 'Maven profile'
        required: false
        default: ''
        type: string
      test_results_artifact_key:
        description: 'The key of the artifact containing the test results'
        required: false
        default: ''
        type: string

env:
  MAVEN_ARGS: '--batch-mode -T 1C --errors --fail-at-end --show-version'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: Download test results
        uses: actions/download-artifact@v4
        if: ${{ inputs.test_results_artifact_key != '' }}
        with:
          name: ${{ inputs.test_results_artifact_key }}
      - name: Test with Maven (verify)
        run: >-
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar -Pcoverage
          -Dsonar.projectKey=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=food2gether
          -Dsonar.qualitygate.wait=true
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          MAVEN_ARGS: ${{ env.MAVEN_ARGS }} ${{ inputs.profile && format('-P%s', inputs.profile) || '' }}

