name: Quarkus Test

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version'
        required: true
        default: '17'
        type: string
      profile:
        description: 'Maven profile'
        required: true
        default: ''
        type: string

env:
  MAVEN_ARGS: '--batch-mode -T 1C --errors --fail-at-end --show-version'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'maven'
      - name: Test with Maven (verify)
        run: ./mvnw verify 
        env:
          MAVEN_ARGS: ${{ env.MAVEN_ARGS }} ${{ inputs.profile && '-P' + inputs.profile || '' }}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test_artifact_name }}
          path: target/**
          include-hidden-files: true
