name: Verify commit

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-jvm:
    uses: food2gether/workflows/.github/workflows/maven-test.yaml@main
    with:
      java_version: '17'