name: Verify Pull Request

on:
  workflow_call:
    inputs:
      sonar-project:
        description: 'Sonar Project Key'
        required: true
    secrets:
      sonar-token:
        description: 'Sonar Token'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-native:
    uses: food2gether/workflows/.github/workflows/maven-test.yaml@main
    with:
      java_version: '17'
      profile: native
      test_results_artifact_key: test-results
  sonar:
    needs: test-native
    uses: food2gether/workflows/.github/workflows/maven-sonar.yaml@main
    with:
      java_version: '17'
      test_results_artifact_key: test-results
      sonar_project_key: ${{ inputs.sonar-project }}
      additional_args: >-
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        -Dsonar.pullrequest.branch=${{ github.head_ref }}
        -Dsonar.pullrequest.base=${{ github.base_ref }}
    secrets:
      sonar_token: ${{ secrets.sonar-token }}