name: Publish frontend

on:
  workflow_call:
    inputs:
      version:
        description: 'Application version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm clean-install
      - name: Build Application
        run: npm run build
      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.version }}
            ghcr.io/${{ github.repository }}:latest
