name: Lint Frontend

on:
  workflow_call:
    inputs:
      {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm clean-install
      - name: Lint with ESLint
        run: npm run lint
